-- Tier 4 recipe: analyze_customer_ltv (generated by scripts/render_tier4_sql.py)
-- Requires migrations 001-004 applied. V105 tier/cdm columns: see v105_metadata.sql
-- Re-run: python scripts/render_tier4_sql.py

BEGIN;

INSERT INTO cookbook_recipe (
    name, display_name, description,
    system_id, module_id, auth_profile_id,
    python_body, entrypoint,
    timeout_seconds, memory_mb,
    is_enabled, is_internal, required_role,
    is_read_only, is_getset, is_batch, is_chainable, is_render_card,
    expected_duration_ms, created_by
)
SELECT
    'analyze_customer_ltv',
    'Analyze Customer LTV',
    'Tier 4: annualized LTV projection from transactions and loyalty.',
    (SELECT id FROM cookbook_system WHERE system_label = 'odoo'),
    (SELECT id FROM cookbook_module WHERE module_label = 'analytics' AND system_id = (SELECT id FROM cookbook_system WHERE system_label = 'odoo')),
    (SELECT id FROM cookbook_auth_profile WHERE profile_label = 'odoo_test'),
    $PY$
"""Tier 4: analyze_customer_ltv — annualized LTV from transaction history and loyalty."""

from __future__ import annotations

from typing import Any, Dict

from recipes._cdm.envelope import success
from recipes.odoo.analytics._recipe import tier4_recipe
from recipes.odoo.analytics._tier4_base import (
    delta_pct,
    dominant_currency,
    trend_from_delta,
    window_totals,
)

RECIPE_NAME = "analyze_customer_ltv"


def _analyze(resolved: Dict[str, Any]) -> Dict[str, Any]:
    transactions = resolved["CommonTransaction"]
    recent_total, prior_total, count = window_totals(transactions, recent_days=365, prior_days=365)
    points = resolved["CommonLoyaltyStatus"].get("points_balance") or 0
    confidence = min(0.95, 0.5 + min(count, 20) * 0.02 + (0.1 if points > 500 else 0))
    pct = delta_pct(recent_total, prior_total)
    return success(
        {
            "annualized_ltv": round(recent_total, 2),
            "currency": dominant_currency(transactions),
            "trend": trend_from_delta(pct),
            "confidence": round(confidence, 2),
        }
    )


run = tier4_recipe(RECIPE_NAME, _analyze, error_message="LTV analysis failed.")

$PY$,
    'run',
    30, 128,
    1, 0, 'user',
    1, 0, 0, 1, 1,
    500, 'tier4-generator'
WHERE NOT EXISTS (SELECT 1 FROM cookbook_recipe WHERE name = 'analyze_customer_ltv');

INSERT INTO cookbook_recipe_var (recipe_id, var_name, var_type, is_required, description, sort_order, created_by)
SELECT r.id, v.var_name, v.var_type, v.is_required, v.description, v.sort_order, 'tier4-generator'
FROM cookbook_recipe r
CROSS JOIN (VALUES
    ('transactions', 'string', 0, 'CommonTransaction JSON array', 10),
    ('loyalty_status', 'string', 0, 'CommonLoyaltyStatus JSON object', 20)
) AS v(var_name, var_type, is_required, description, sort_order)
WHERE r.name = 'analyze_customer_ltv'
ON CONFLICT (recipe_id, var_name) DO NOTHING;

INSERT INTO cookbook_recipe_output (recipe_id, output_key, source_path, value_type, is_required, description, display_label, sort_order, created_by)
SELECT r.id, o.output_key, 'data', o.value_type, o.is_required, o.description, o.display_label, o.sort_order, 'tier4-generator'
FROM cookbook_recipe r
CROSS JOIN (VALUES
    ('ltv_projection', 'object', 1, 'LTVProjection result', 'LTV Projection', 10)
) AS o(output_key, _src, value_type, is_required, description, display_label, sort_order)
WHERE r.name = 'analyze_customer_ltv'
ON CONFLICT (recipe_id, output_key) DO NOTHING;

COMMIT;
