-- Tier 4 recipe: analyze_spend_trend (generated by scripts/render_tier4_sql.py)
-- Requires migrations 001-004 applied. V105 tier/cdm columns: see v105_metadata.sql
-- Re-run: python scripts/render_tier4_sql.py

BEGIN;

INSERT INTO cookbook_recipe (
    name, display_name, description,
    system_id, module_id, auth_profile_id,
    python_body, entrypoint,
    timeout_seconds, memory_mb,
    is_enabled, is_internal, required_role,
    is_read_only, is_getset, is_batch, is_chainable, is_render_card,
    expected_duration_ms, created_by
)
SELECT
    'analyze_spend_trend',
    'Analyze Spend Trend',
    'Tier 4: weekly spend buckets and prior-period delta from CommonTransaction.',
    (SELECT id FROM cookbook_system WHERE system_label = 'odoo'),
    (SELECT id FROM cookbook_module WHERE module_label = 'analytics' AND system_id = (SELECT id FROM cookbook_system WHERE system_label = 'odoo')),
    (SELECT id FROM cookbook_auth_profile WHERE profile_label = 'odoo_test'),
    $PY$
"""Tier 4: analyze_spend_trend — weekly spend buckets and prior-period delta."""

from __future__ import annotations

from collections import defaultdict
from datetime import datetime
from typing import Any, Dict, List

from recipes._cdm.envelope import success
from recipes.odoo.analytics._recipe import tier4_recipe
from recipes.odoo.analytics._tier4_base import (
    delta_pct,
    iter_transactions,
    parse_iso_date,
    period_totals,
    trend_from_delta,
    tx_amount,
)

RECIPE_NAME = "analyze_spend_trend"
_EMPTY = {
    "period": "weekly",
    "buckets": [],
    "total_current": 0.0,
    "total_prior": 0.0,
    "delta_pct": 0.0,
    "trend": "flat",
}


def _week_key(dt: datetime) -> str:
    iso = dt.isocalendar()
    return f"{iso.year}-W{iso.week:02d}"


def _weekly_buckets(transactions: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    buckets: Dict[str, float] = defaultdict(float)
    for tx in iter_transactions(transactions):
        if dt := parse_iso_date(tx.get("date")):
            buckets[_week_key(dt)] += tx_amount(tx)
    return [{"week": week, "total": round(amount, 2)} for week, amount in sorted(buckets.items())]


def _analyze(resolved: Dict[str, Any]) -> Dict[str, Any]:
    transactions = resolved["CommonTransaction"]
    if not transactions:
        return success(_EMPTY, user_message="No transactions to analyze.")

    total_current, total_prior = period_totals(transactions)
    pct = delta_pct(total_current, total_prior)
    return success(
        {
            "period": "weekly",
            "buckets": _weekly_buckets(transactions),
            "total_current": round(total_current, 2),
            "total_prior": round(total_prior, 2),
            "delta_pct": pct,
            "trend": trend_from_delta(pct),
        }
    )


run = tier4_recipe(RECIPE_NAME, _analyze, error_message="Spend trend analysis failed.")

$PY$,
    'run',
    30, 128,
    1, 0, 'user',
    1, 0, 0, 1, 1,
    500, 'tier4-generator'
WHERE NOT EXISTS (SELECT 1 FROM cookbook_recipe WHERE name = 'analyze_spend_trend');

INSERT INTO cookbook_recipe_var (recipe_id, var_name, var_type, is_required, description, sort_order, created_by)
SELECT r.id, v.var_name, v.var_type, v.is_required, v.description, v.sort_order, 'tier4-generator'
FROM cookbook_recipe r
CROSS JOIN (VALUES
    ('transactions', 'string', 0, 'CommonTransaction JSON array', 10)
) AS v(var_name, var_type, is_required, description, sort_order)
WHERE r.name = 'analyze_spend_trend'
ON CONFLICT (recipe_id, var_name) DO NOTHING;

INSERT INTO cookbook_recipe_output (recipe_id, output_key, source_path, value_type, is_required, description, display_label, sort_order, created_by)
SELECT r.id, o.output_key, 'data', o.value_type, o.is_required, o.description, o.display_label, o.sort_order, 'tier4-generator'
FROM cookbook_recipe r
CROSS JOIN (VALUES
    ('spend_trend', 'object', 1, 'SpendTrend analysis result', 'Spend Trend', 10)
) AS o(output_key, _src, value_type, is_required, description, display_label, sort_order)
WHERE r.name = 'analyze_spend_trend'
ON CONFLICT (recipe_id, output_key) DO NOTHING;

COMMIT;
