-- Tier 4 recipe: analyze_inventory_gaps (generated by scripts/render_tier4_sql.py)
-- Requires migrations 001-004 applied. V105 tier/cdm columns: see v105_metadata.sql
-- Re-run: python scripts/render_tier4_sql.py

BEGIN;

INSERT INTO cookbook_recipe (
    name, display_name, description,
    system_id, module_id, auth_profile_id,
    python_body, entrypoint,
    timeout_seconds, memory_mb,
    is_enabled, is_internal, required_role,
    is_read_only, is_getset, is_batch, is_chainable, is_render_card,
    expected_duration_ms, created_by
)
SELECT
    'analyze_inventory_gaps',
    'Analyze Inventory Gaps',
    'Tier 4: stockout risk from inventory snapshots and transaction velocity.',
    (SELECT id FROM cookbook_system WHERE system_label = 'odoo'),
    (SELECT id FROM cookbook_module WHERE module_label = 'analytics' AND system_id = (SELECT id FROM cookbook_system WHERE system_label = 'odoo')),
    (SELECT id FROM cookbook_auth_profile WHERE profile_label = 'odoo_test'),
    $PY$
"""Tier 4: analyze_inventory_gaps — stockout risk from snapshots and transaction velocity."""

from __future__ import annotations

from datetime import timedelta
from typing import Any, Dict, List

from recipes._cdm.envelope import success
from recipes.odoo.analytics._recipe import tier4_recipe
from recipes.odoo.analytics._tier4_base import (
    iso_timestamp_z,
    iter_transactions,
    sum_line_item_qty_by_product,
    utc_now,
)

RECIPE_NAME = "analyze_inventory_gaps"
LOOKBACK_DAYS = 90
_SEVERITY_ORDER = {"critical": 0, "warning": 1, "ok": 2}


def _daily_velocity(transactions: List[Dict[str, Any]]) -> Dict[str, float]:
    cutoff = utc_now() - timedelta(days=LOOKBACK_DAYS)
    qty_by_product = sum_line_item_qty_by_product(list(iter_transactions(transactions, since=cutoff)))
    return {pid: qty / LOOKBACK_DAYS for pid, qty in qty_by_product.items()}


def _severity(
    days_to_stockout: float | None,
    qty_available: float,
    reorder_point: float | None,
) -> str:
    if days_to_stockout is None:
        return "ok"
    if reorder_point is not None and qty_available <= reorder_point:
        return "critical"
    if days_to_stockout <= 7:
        return "critical"
    if days_to_stockout <= 14:
        return "warning"
    return "ok"


def _gap_row(snap: Dict[str, Any], velocity: Dict[str, float]) -> Dict[str, Any]:
    product_id = str(snap.get("product_id", ""))
    qty_available = float(snap.get("qty_available") or 0)
    daily = velocity.get(product_id, 0.0)
    reorder = snap.get("reorder_point")
    reorder_f = float(reorder) if reorder is not None else None
    days_to_stockout = round(qty_available / daily, 1) if daily > 0 else None
    return {
        "product_id": product_id,
        "location_name": snap.get("location_name"),
        "qty_available": qty_available,
        "sales_velocity_per_day": round(daily, 4),
        "days_to_stockout": days_to_stockout,
        "severity": _severity(days_to_stockout, qty_available, reorder_f),
    }


def _analyze(resolved: Dict[str, Any]) -> Dict[str, Any]:
    velocity = _daily_velocity(resolved["CommonTransaction"])
    gaps = [_gap_row(snap, velocity) for snap in resolved["CommonInventorySnapshot"]]
    gaps.sort(
        key=lambda g: (
            _SEVERITY_ORDER.get(g["severity"], 9),
            g["days_to_stockout"] if g["days_to_stockout"] is not None else 9999,
        )
    )
    return success({"as_of": iso_timestamp_z(), "gaps": gaps})


run = tier4_recipe(RECIPE_NAME, _analyze, error_message="Inventory gap analysis failed.")

$PY$,
    'run',
    30, 128,
    1, 0, 'user',
    1, 0, 0, 1, 1,
    500, 'tier4-generator'
WHERE NOT EXISTS (SELECT 1 FROM cookbook_recipe WHERE name = 'analyze_inventory_gaps');

INSERT INTO cookbook_recipe_var (recipe_id, var_name, var_type, is_required, description, sort_order, created_by)
SELECT r.id, v.var_name, v.var_type, v.is_required, v.description, v.sort_order, 'tier4-generator'
FROM cookbook_recipe r
CROSS JOIN (VALUES
    ('transactions', 'string', 0, 'CommonTransaction JSON array', 10),
    ('inventory_snapshots', 'string', 0, 'CommonInventorySnapshot JSON array', 20)
) AS v(var_name, var_type, is_required, description, sort_order)
WHERE r.name = 'analyze_inventory_gaps'
ON CONFLICT (recipe_id, var_name) DO NOTHING;

INSERT INTO cookbook_recipe_output (recipe_id, output_key, source_path, value_type, is_required, description, display_label, sort_order, created_by)
SELECT r.id, o.output_key, 'data', o.value_type, o.is_required, o.description, o.display_label, o.sort_order, 'tier4-generator'
FROM cookbook_recipe r
CROSS JOIN (VALUES
    ('gap_report', 'object', 1, 'GapReport with per-product risk', 'Gap Report', 10)
) AS o(output_key, _src, value_type, is_required, description, display_label, sort_order)
WHERE r.name = 'analyze_inventory_gaps'
ON CONFLICT (recipe_id, output_key) DO NOTHING;

COMMIT;
