-- Tier 4 recipe: analyze_store_session_metrics (generated by scripts/render_tier4_sql.py)
-- Requires migrations 001-004 applied. V105 tier/cdm columns: see v105_metadata.sql
-- Re-run: python scripts/render_tier4_sql.py

BEGIN;

INSERT INTO cookbook_recipe (
    name, display_name, description,
    system_id, module_id, auth_profile_id,
    python_body, entrypoint,
    timeout_seconds, memory_mb,
    is_enabled, is_internal, required_role,
    is_read_only, is_getset, is_batch, is_chainable, is_render_card,
    expected_duration_ms, created_by
)
SELECT
    'analyze_store_session_metrics',
    'Analyze Store Session Metrics',
    'Tier 4: aggregate kiosk session metrics.',
    (SELECT id FROM cookbook_system WHERE system_label = 'odoo'),
    (SELECT id FROM cookbook_module WHERE module_label = 'analytics' AND system_id = (SELECT id FROM cookbook_system WHERE system_label = 'odoo')),
    (SELECT id FROM cookbook_auth_profile WHERE profile_label = 'odoo_test'),
    $PY$
"""Tier 4: analyze_store_session_metrics — aggregate kiosk session metrics."""

from __future__ import annotations

from collections import Counter
from typing import Any, Dict, List

from recipes._cdm.envelope import success
from recipes.odoo.analytics._recipe import tier4_recipe

RECIPE_NAME = "analyze_store_session_metrics"
_EMPTY = {
    "session_count": 0,
    "conversion_rate": 0.0,
    "top_intents": [],
    "avg_duration_seconds": 0.0,
}


def _analyze(resolved: Dict[str, Any]) -> Dict[str, Any]:
    sessions: List[Dict[str, Any]] = resolved["CommonKioskSession"]
    if not sessions:
        return success(_EMPTY, user_message="No kiosk sessions to analyze.")

    durations = [
        int(s["duration_seconds"])
        for s in sessions
        if isinstance(s.get("duration_seconds"), (int, float))
    ]
    intents = Counter(str(s["intent"]) for s in sessions if s.get("intent"))
    converted = sum(1 for s in sessions if s.get("converted"))
    count = len(sessions)

    return success(
        {
            "session_count": count,
            "conversion_rate": round(converted / count, 4),
            "top_intents": [{"intent": name, "count": n} for name, n in intents.most_common(5)],
            "avg_duration_seconds": round(sum(durations) / len(durations), 1) if durations else 0.0,
        }
    )


run = tier4_recipe(RECIPE_NAME, _analyze, error_message="Session metrics analysis failed.")

$PY$,
    'run',
    30, 128,
    1, 0, 'user',
    1, 0, 0, 1, 1,
    500, 'tier4-generator'
WHERE NOT EXISTS (SELECT 1 FROM cookbook_recipe WHERE name = 'analyze_store_session_metrics');

INSERT INTO cookbook_recipe_var (recipe_id, var_name, var_type, is_required, description, sort_order, created_by)
SELECT r.id, v.var_name, v.var_type, v.is_required, v.description, v.sort_order, 'tier4-generator'
FROM cookbook_recipe r
CROSS JOIN (VALUES
    ('kiosk_sessions', 'string', 0, 'CommonKioskSession JSON array', 10)
) AS v(var_name, var_type, is_required, description, sort_order)
WHERE r.name = 'analyze_store_session_metrics'
ON CONFLICT (recipe_id, var_name) DO NOTHING;

INSERT INTO cookbook_recipe_output (recipe_id, output_key, source_path, value_type, is_required, description, display_label, sort_order, created_by)
SELECT r.id, o.output_key, 'data', o.value_type, o.is_required, o.description, o.display_label, o.sort_order, 'tier4-generator'
FROM cookbook_recipe r
CROSS JOIN (VALUES
    ('session_metrics', 'object', 1, 'SessionMetrics result', 'Session Metrics', 10)
) AS o(output_key, _src, value_type, is_required, description, display_label, sort_order)
WHERE r.name = 'analyze_store_session_metrics'
ON CONFLICT (recipe_id, output_key) DO NOTHING;

COMMIT;
