-- Tier 4 recipe: analyze_churn_signals (generated by scripts/render_tier4_sql.py)
-- Requires migrations 001-004 applied. V105 tier/cdm columns: see v105_metadata.sql
-- Re-run: python scripts/render_tier4_sql.py

BEGIN;

INSERT INTO cookbook_recipe (
    name, display_name, description,
    system_id, module_id, auth_profile_id,
    python_body, entrypoint,
    timeout_seconds, memory_mb,
    is_enabled, is_internal, required_role,
    is_read_only, is_getset, is_batch, is_chainable, is_render_card,
    expected_duration_ms, created_by
)
SELECT
    'analyze_churn_signals',
    'Analyze Churn Signals',
    'Tier 4: churn score from profile, transactions, and open tickets.',
    (SELECT id FROM cookbook_system WHERE system_label = 'odoo'),
    (SELECT id FROM cookbook_module WHERE module_label = 'analytics' AND system_id = (SELECT id FROM cookbook_system WHERE system_label = 'odoo')),
    (SELECT id FROM cookbook_auth_profile WHERE profile_label = 'odoo_test'),
    $PY$
"""Tier 4: analyze_churn_signals — churn score from profile, transactions, and tickets."""

from __future__ import annotations

from typing import Any, Dict, List

from recipes._cdm.envelope import success
from recipes.odoo.analytics._recipe import tier4_recipe
from recipes.odoo.analytics._tier4_base import (
    OPEN_TICKET_STATUSES,
    accumulate_scores,
    filter_by_status,
    last_paid_transaction_date,
    normalize_status,
    parse_iso_date,
    utc_now,
)

RECIPE_NAME = "analyze_churn_signals"


def _risk_level(score: int) -> str:
    if score >= 60:
        return "high"
    if score >= 35:
        return "medium"
    return "low"


def _score_from_recency(last_seen_at: str | None) -> tuple[int, List[str]]:
    last_seen = parse_iso_date(last_seen_at or "")
    if not last_seen:
        return 15, ["missing_last_seen_at"]
    days_idle = (utc_now() - last_seen).days
    if days_idle > 180:
        return 40, ["last_seen_over_180_days"]
    if days_idle > 90:
        return 25, ["last_seen_over_90_days"]
    return 0, []


def _score_from_transactions(transactions: List[Dict[str, Any]]) -> tuple[int, List[str]]:
    last_paid = last_paid_transaction_date(transactions)
    if not last_paid:
        return 20, ["no_paid_transactions"]
    gap_days = (utc_now() - last_paid).days
    if gap_days > 120:
        return 30, ["last_purchase_over_120_days"]
    if gap_days > 60:
        return 15, ["purchase_gap_increased"]
    return 0, []


def _score_from_tickets(tickets: List[Dict[str, Any]]) -> tuple[int, List[str]]:
    open_tickets = filter_by_status(tickets, OPEN_TICKET_STATUSES)
    if not open_tickets:
        return 0, []
    factors = ["open_service_tickets"]
    score = min(25, 10 + len(open_tickets) * 5)
    if any(normalize_status(t.get("priority")) in ("high", "urgent") for t in open_tickets):
        factors.append("open_complaint_ticket")
    if any(normalize_status(t.get("priority")) == "urgent" for t in open_tickets):
        score += 10
        factors.append("urgent_open_ticket")
    return score, factors


def _analyze(resolved: Dict[str, Any]) -> Dict[str, Any]:
    score, risk_factors = accumulate_scores(
        lambda: _score_from_recency(resolved["CommonCustomerProfile"].get("last_seen_at")),
        lambda: _score_from_transactions(resolved["CommonTransaction"]),
        lambda: _score_from_tickets(resolved["CommonServiceTicket"]),
    )
    score = min(100, score)
    return success(
        {
            "score": score,
            "risk_level": _risk_level(score),
            "risk_factors": risk_factors,
        }
    )


run = tier4_recipe(RECIPE_NAME, _analyze, error_message="Churn analysis failed.")

$PY$,
    'run',
    30, 128,
    1, 0, 'user',
    1, 0, 0, 1, 1,
    500, 'tier4-generator'
WHERE NOT EXISTS (SELECT 1 FROM cookbook_recipe WHERE name = 'analyze_churn_signals');

INSERT INTO cookbook_recipe_var (recipe_id, var_name, var_type, is_required, description, sort_order, created_by)
SELECT r.id, v.var_name, v.var_type, v.is_required, v.description, v.sort_order, 'tier4-generator'
FROM cookbook_recipe r
CROSS JOIN (VALUES
    ('customer_profile', 'string', 0, 'CommonCustomerProfile JSON object', 10),
    ('transactions', 'string', 0, 'CommonTransaction JSON array', 20),
    ('service_tickets', 'string', 0, 'CommonServiceTicket JSON array', 30)
) AS v(var_name, var_type, is_required, description, sort_order)
WHERE r.name = 'analyze_churn_signals'
ON CONFLICT (recipe_id, var_name) DO NOTHING;

INSERT INTO cookbook_recipe_output (recipe_id, output_key, source_path, value_type, is_required, description, display_label, sort_order, created_by)
SELECT r.id, o.output_key, 'data', o.value_type, o.is_required, o.description, o.display_label, o.sort_order, 'tier4-generator'
FROM cookbook_recipe r
CROSS JOIN (VALUES
    ('churn_score', 'object', 1, 'ChurnScore result', 'Churn Score', 10)
) AS o(output_key, _src, value_type, is_required, description, display_label, sort_order)
WHERE r.name = 'analyze_churn_signals'
ON CONFLICT (recipe_id, output_key) DO NOTHING;

COMMIT;
