-- Tier 4 recipe: analyze_customer_segment (generated by scripts/render_tier4_sql.py)
-- Requires migrations 001-004 applied. V105 tier/cdm columns: see v105_metadata.sql
-- Re-run: python scripts/render_tier4_sql.py

BEGIN;

INSERT INTO cookbook_recipe (
    name, display_name, description,
    system_id, module_id, auth_profile_id,
    python_body, entrypoint,
    timeout_seconds, memory_mb,
    is_enabled, is_internal, required_role,
    is_read_only, is_getset, is_batch, is_chainable, is_render_card,
    expected_duration_ms, created_by
)
SELECT
    'analyze_customer_segment',
    'Analyze Customer Segment',
    'Tier 4: heuristic segment profile from transaction history.',
    (SELECT id FROM cookbook_system WHERE system_label = 'odoo'),
    (SELECT id FROM cookbook_module WHERE module_label = 'analytics' AND system_id = (SELECT id FROM cookbook_system WHERE system_label = 'odoo')),
    (SELECT id FROM cookbook_auth_profile WHERE profile_label = 'odoo_test'),
    $PY$
"""Tier 4: analyze_customer_segment — heuristic cohort summary from transactions."""

from __future__ import annotations

from typing import Any, Dict

from recipes._cdm.envelope import success
from recipes.odoo.analytics._recipe import tier4_recipe
from recipes.odoo.analytics._tier4_base import (
    iter_transactions,
    sum_line_item_qty_by_product,
    top_k_items,
    tx_amount,
)

RECIPE_NAME = "analyze_customer_segment"
_EMPTY = {
    "segment_label": "no_activity",
    "avg_order_value": 0.0,
    "top_products": [],
    "order_count": 0,
}


def _segment_label(avg_order_value: float) -> str:
    if avg_order_value >= 500:
        return "high_value"
    if avg_order_value >= 150:
        return "mid_value"
    return "value_shopper"


def _analyze(resolved: Dict[str, Any]) -> Dict[str, Any]:
    active = list(iter_transactions(resolved["CommonTransaction"]))
    if not active:
        return success(_EMPTY, user_message="No transactions for segmentation.")

    totals = [tx_amount(tx) for tx in active]
    order_count = len(totals)
    avg_order_value = round(sum(totals) / order_count, 2)
    return success(
        {
            "segment_label": _segment_label(avg_order_value),
            "avg_order_value": avg_order_value,
            "top_products": top_k_items(sum_line_item_qty_by_product(active)),
            "order_count": order_count,
        }
    )


run = tier4_recipe(RECIPE_NAME, _analyze, error_message="Segment analysis failed.")

$PY$,
    'run',
    30, 128,
    1, 0, 'user',
    1, 0, 0, 1, 1,
    500, 'tier4-generator'
WHERE NOT EXISTS (SELECT 1 FROM cookbook_recipe WHERE name = 'analyze_customer_segment');

INSERT INTO cookbook_recipe_var (recipe_id, var_name, var_type, is_required, description, sort_order, created_by)
SELECT r.id, v.var_name, v.var_type, v.is_required, v.description, v.sort_order, 'tier4-generator'
FROM cookbook_recipe r
CROSS JOIN (VALUES
    ('transactions', 'string', 0, 'CommonTransaction JSON array', 10)
) AS v(var_name, var_type, is_required, description, sort_order)
WHERE r.name = 'analyze_customer_segment'
ON CONFLICT (recipe_id, var_name) DO NOTHING;

INSERT INTO cookbook_recipe_output (recipe_id, output_key, source_path, value_type, is_required, description, display_label, sort_order, created_by)
SELECT r.id, o.output_key, 'data', o.value_type, o.is_required, o.description, o.display_label, o.sort_order, 'tier4-generator'
FROM cookbook_recipe r
CROSS JOIN (VALUES
    ('segment_profile', 'object', 1, 'SegmentProfile result', 'Segment', 10)
) AS o(output_key, _src, value_type, is_required, description, display_label, sort_order)
WHERE r.name = 'analyze_customer_segment'
ON CONFLICT (recipe_id, output_key) DO NOTHING;

COMMIT;
