[options]
admin_passwd = $pbkdf2-sha512$600000$ag2hVGoNAWAsxdh7j3FOCQ$74/pNqtHym5LUchaFqJUpMCe4q0Xb3xyDi0RSsw2EQOVHDnyPNHYKwtABhI6QpZFURR1Ga3a6fQqL/QvZPpCQQ
addons_path = /mnt/extra-addons
log_level = info
